package negocio;

import controlador.Sistema;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Jugador.java
//  @ Date : 22/5/2018
//  @ Author : 
//
//




public class Jugador {	
	private int credito;
	private int idMaquina;
	private int idJugador;
	
	public Jugador(int credito, int idMaquina, int idJugador) {
		this.credito = credito;
		this.idMaquina = idMaquina;
		this.setIdJugador(idJugador);
	}
	public boolean tengoCredito(int id) {
		Sistema controlador = Sistema.getSingletonInstance();
		return (credito < controlador.getPrecioJugada(id));
	}
	
	public int getCredito() {
		return credito;
	}

	public void setCredito(int credito) {
		this.credito = credito;
	}
	
	public void aumentarCredito(int x) {
		this.credito = this.credito + x;
	}

	public int getIdMaquina() {
		return idMaquina;
	}

	public int getIdJugador() {
		return idJugador;
	}

	public void setIdJugador(int idJugador) {
		this.idJugador = idJugador;
	}	
	
}
