package negocio;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Premio.java
//  @ Date : 22/5/2018
//  @ Author : 
//
//




public class Premio {
	public Premio(int valor, int idMaquina, ArrayList<String> combinacion) {
		this.valor = valor;
		this.idMaquina = idMaquina;
		this.combinacion = combinacion;
	}
	private int valor;
	private int idMaquina;
	private ArrayList<String> combinacion;
		
	public boolean soy(ArrayList<String> combinacion) {			
		ArrayList<String> aux = new ArrayList<String>(combinacion); //copio la combinacion de entrada
			
		for (int i = 0; i < this.combinacion.size(); i++) //por cada fruta en la combinacion del premio
			for(int j=0; j < aux.size(); j++) //y por cada fruta en la combinacion de entrada
				if(this.combinacion.get(i).toUpperCase().equals(aux.get(j).toUpperCase())) { //si las frutas, en mayuscula, son iguales
					aux.remove(aux.get(j));//quito esa fruta de la combinacion
					i++;//paso a la siguiente fruta del premio
				}//si ambas combinaciones son iguales, el arreglo auxiliar será vacío
	
		return aux.isEmpty();//por lo que devuelve true solamente si son iguales
	}

	public int getValor() {
		return valor;
	}


	public ArrayList<String> getCombinacion() {
		return combinacion;
	}
}
